### ISSUE TITLE
Numpy data type incompatability

### ISSUE THREAD

**Issue by KulikDM** [mljar/supertree#10]
Hi, so glad to see a project like this. Super helpful!

While testing I ran into an error where numpy did not support `np.float128`.
It seems this is less a numpy version thing, but rather  `np.float128` is available only for some OS or machine architectures.

Anyways this was the quick fix that I applied in `node.py` and `treedata.py`. I changed:

```
if isinstance(value, (np.float16, np.float32, np.float64, np.float128)):
```

to 

```
if isinstance(value, (np.float16, np.float32, np.float64) + getattr(np, 'float128', ())):
```

And it worked fine!

For specs I had:
python 3.9
numpy=1.23.5
latest ipython
Windows 10
Intel i9 9th gen

**Comment by Marchlak** [comment]
I’ll implement this fix in the next release of the package, which will also add the ability to display the path to a specific leaf node. However, there’s still a bit of work left to do on that. Thank you so much for catching this issue! I want "supertree" to work on every operating system, and I haven’t had the chance to test it on Windows yet. Your help is truly appreciated! I’ll make sure to notify you once the new version is released.

**Comment by KulikDM** [comment]
@Marchlak thanks for your response and an absolute pleasure to be of some help. Hope that everyone sees "supertree" for what it is... a gem!

**Comment by Marchlak** [comment]
Hi, the bug has been fixed in the latest version of supertree.
