### ISSUE TITLE
Error with categorical features

### ISSUE THREAD

**Issue by Thornam** [mljar/supertree#14]
When using categorical features that aren't binary, I experience an error in the show_tree().

![image](https://github.com/user-attachments/assets/3c147c3c-10e9-4255-99a6-47a5a878d8f5)

As far as I can see, when trying to debug, it seems that the error is caused because splits on categorical features have more than one threshold, causing the threshold not to be a float variable.

**Comment by pplonski** [comment]
Hi @Thornam,

Thank you for reporting the issue. What algorithm are you using for trees? Could you please provide code to reproduce the issue? so we can fix the problem. Thank you!

**Comment by Thornam** [comment]
Thanks! It does work now for categorical data with the LGBM, both in the example and in my original problem.

**Comment by pplonski** [comment]
Good job @Marchlak :1st_place_medal:
