### ISSUE TITLE
Support for HistGradientBoostingRegressor

### ISSUE THREAD

**Issue by ogencoglu** [mljar/supertree#2]
Histogram-based gradient boosting support would be great!

**Comment by Marchlak** [comment]
Thank you for your suggestion! I’ve added support for the HistGradientBoosting models, and you can now test them. If you encounter any issues with this model, please let me know, and I will address them promptly.

Regarding your other request for ONNX support, we appreciate your input and plan to add this support in the near future, as long as it’s feasible. Thank you again for your valuable suggestions!

**Comment by ogencoglu** [comment]
Thanks for the swift reply!

**Comment by ogencoglu** [comment]
Also readme can be updated.
