### ISSUE TITLE
Visualize arbitrary trees

### ISSUE THREAD

**Issue by fzyzcjy** [mljar/supertree#23]
Hi thanks for the library! I have some search trees (e.g. from BFS/DFS etc), and would like to visualize it. Is it possible to use this?

**Comment by Marchlak** [comment]
Theoretically, it is possible, and you can see this in a limited way in the example/CustomTreeExample.ipynb directory. However, for some algorithmic problems, the visualization would probably need to look a bit different. Most likely, a node would be a circle of some color, with a certain value inside the node, and both the edges and the values on the edges would have their own colors. At the moment, we are focusing on decision trees, but we might add this type of visualization in the future. You can send an example tree that you would like to visualize, along with the type of visualization you would expect.

**Comment by fzyzcjy** [comment]
I see, thank you!
