### ISSUE TITLE
How to cite

### ISSUE THREAD

**Issue by SalvatoreRa** [mljar/supertree#4]
Hi,

Terrific work. I am writing a review on interpretable machine learning, how I can cite this repository?

have a nice day

**Comment by pplonski** [comment]
Hi @SalvatoreRa,

This is great work done by @Marchlak :1st_place_medal: Please find citation details in https://github.com/mljar/supertree/blob/main/CITATION

I would love to read your review, please share it with us when ready, by email contact@mljar.com or LinkedIn. Thank you!

All the best,
Piotr

**Comment by SalvatoreRa** [comment]
Thank you,

and again, great work. I will share it with you when it is ready. we are still writing and preparing figures
